### ISSUE TITLE
Add mention of tideways_xhprof as alternative PHP extension dependency

### ISSUE THREAD

**Issue by yorkshire-pudding** [backdrop-contrib/webprofiler#1]
@hosef - I saw this and gave it a quick test; looks interesting and potentially useful if there are performance issues.
On my cPanel hosting, I didn't have the option for `xhprof` but did have `tideways_xhprof` and it works with this enabled.  Might be worth mentioning that either of these will work.

**Comment by hosef** [comment]
I checked the Tideways repository, and it has been archived in favor of using the version of xhprof from PECL. I am going to close this issue, since it does not seem relevant any more.
