### ISSUE TITLE
xhprof for different php versions on Windows OS

### ISSUE THREAD

**Issue by izmeez** [backdrop-contrib/webprofiler#3]
The version of xhprof to use depends on the php version. Here is a link to download xhprof for different php versions on Windows OS, https://windows.php.net/downloads/pecl/releases/xhprof/

It may be useful to add this to the Readme file.

**Comment by izmeez** [comment]
The same information can be found using the current link in the readme. When a user clicks on the Windows icon with the DLL text it takes them to a page that provides links for different php versions. Maybe the extra link isn't really needed in the Readme file?

**Comment by hosef** [comment]
The main xhprof page has links to the Windows versions, so I think we should be fine with the link that is already there.
